# Generated by Django 5.2.6 on 2025-10-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='session_key',
            field=models.CharField(db_index=True, default=1, max_length=40),
            preserve_default=False,
        ),
    ]
